apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    k8s-app: spring-app
spec:
  selector:
    matchLabels:
      k8s-app: spring-app
  template:
    metadata:
      labels:
        k8s-app: spring-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: spring-app
          image: vlavrynovych/prometheus
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  labels:
    k8s-app: spring-app
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  selector:
    k8s-app: spring-app
status:
  loadBalancer: {}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-app-service-monitor
  labels:
    release: prometheus
    k8s-app: spring-app-service-monitor
spec:
  endpoints:
    - interval: 5s
      targetPort: 8080
      path: "/actuator/prometheus"
  selector:
    matchLabels:
      k8s-app: spring-app